# Generated by Django 3.2.7 on 2021-09-25 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default=uuid.uuid4, max_length=36, verbose_name='Order')),
                ('points', models.PositiveIntegerField(help_text='Eg. 14', verbose_name='Poins')),
                ('subtotal', models.FloatField(help_text='Eg. 100.0', verbose_name='Subtotal')),
                ('tax', models.FloatField(default=0.0, help_text='Eg. 16.00', null=True, verbose_name='Tax (IVA)')),
                ('grand_total', models.FloatField(help_text='Eg. 100.0', verbose_name='Grand Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'ordering': ('created_at',),
            },
        ),
    ]
