# Generated by Django 3.2.7 on 2021-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, null=True)),
                ('start', models.DateTimeField(default='27/09/2021 00:00:00', verbose_name='Start')),
                ('end', models.DateTimeField(default='03/10/2021 00:00:00', verbose_name='End')),
                ('complete', models.DateTimeField(verbose_name='Complete Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ('created_at',),
            },
        ),
    ]
