# Generated by Django 3.2.7 on 2021-09-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Product description as content, color, uses cases.', null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m/%d', verbose_name='Image')),
                ('price', models.FloatField(help_text='Eg. 100.0', verbose_name='Price')),
                ('points', models.PositiveIntegerField(help_text='Eg. 14', verbose_name='Poins')),
                ('tax', models.FloatField(help_text='Eg. 16', null=True, verbose_name='Tax (IVA)')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
    ]
